# This is a basic workflow that is manually triggered

name: Sample workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.

on:

  push:

    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "greet"

  greet:

    # The type and label of runner that the job will run on

    runs-on: [self-hosted, spot]

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

    # Runs a single command using the runners shell

    - name: Send greetings

      run: echo "Hello ${{ github.event.inputs.name }}"

    - run: sleep 300

